config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'users/new'
  root 'pages#index'


  get 'user/:id', to: 'posts#user_posts', as: 'user_infos'

  resources :posts do
    resources :comments
  end

  # error pages
  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: true
  validates :content, presence: true

  has_many :comments
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  before_action :set_locale

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  def set_locale
    I18n.locale = params[:locale]
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_post



  def create
   @comment = @post.comments.create(params[:comment].permit(:body).merge(user: current_user))
   redirect_to post_path(@post)
 end

 def destroy
   @comment = @post.comments.find(params[:id])
   @comment.destroy
   redirect_to post_path(@post)
 end

 def edit
   @comment = Comment.find(params[:id])
   @post = Post.find(params[:post_id])
 end

  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.update(params[:comment].permit(:body).merge(user: current_user))
    redirect_to @post
  end



  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def index
    @posts = Post.all
    require 'open-uri'
    require 'json'

    @content = URI("https://newsapi.org/v2/top-headlines?sources=abc-news&apiKey=dd1a011b861d44118163582bc4df2195").read
    @content = JSON.parse(@content)
  endcale =  params[:locale]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy]


  def index
    @posts = Post.all
  end

  def show
  end

  def edit
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params.merge(user: current_user))
    if @post.persisted?
      redirect_to posts_url, notice: "L'article a bien été créé"
    else
      render :new
    end
  end

  def update
    if @post.user == current_user
      if @post.update(post_params)
        redirect_to posts_url, notice: "l'article a bien été modifié"
      else
        render :edit
      end
    else
      redirect_to posts_url, notice: "Vous n'etes pas propriétaire"
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: "Le fichier a bien été supprimé"
  end

  def user_posts
    @user = User.find(params[:id])
    @posts = Post.where(user: @user)
  end

  private

  def set_post
    @post = Post.find(params[:id])

  end

  def post_params
    params.require(:post).permit('title', 'content')
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div class="row">
  <section class="col s12 m4">
    <h5><%= comment.user.username %> </h5>
    <p><%= comment.body %> </p>
    <p>
      <%= time_ago_in_words(comment.created_at) %>
      <% if current_user == comment.user %>
        <%= link_to 'Editer', edit_post_comment_path(post_id: @post.id, id: comment.id) %>
      <% end %>
      <% if current_user == comment.user || current_user == @post.user %>
        <%= link_to t("post.delete"), post_comment_path(@post, comment), method: :delete %>
      <% end %>
    </p>
    <div class="col s12 divider"></div>
  </section>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post,@post.comments.build]) do |f| %>
  <p>
    <%= f.label :body %> <br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Commenter' %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<%= form_for([@post, @comment]) do |f| %>

  <p>
    <%= f.label :body %> <br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Publier' %>
  </p>
<% end %>git

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Materialize -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  <!-- end Materialize -->


  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body>

<nav>
  <div class="nav-wrapper">
    <div class="container">
      <%= link_to t("header.home"), root_path, class: 'brand-logo' %>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if current_user %>
          <li><%= link_to 'Articles', posts_path %></li>
          <li><%= link_to current_user.username, user_infos_path(id: current_user.id) %></li>
          <li>
            <%= link_to destroy_user_session_path, :method => 'delete' do %>
              <i class="material-icons">power_settings_new</i>
            <% end %>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_session_path(resource_name) %><br /></li>
          <li><%= link_to "Sign up", new_registration_path(resource_name) %></li>
        <% end %>
        <li><%= link_to 'En', url_for( :locale => 'en' ) %></li>
        <li><%= link_to 'Fr', url_for( :locale => 'fr' ) %></li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/news/_new.html.erb
<div class="col s12 m6">
  <div class="card">
    <div class="card-image">
      <img src="<%= article['urlToImage'] %>">
      <span class="card-title"><%= article['title'] %></span>
    </div>
    <div class="card-content">
      <p><%= article['description'] %></p>
    </div>
    <div class="card-action">
      <a href="<%= article['url'] %>">Link to the article</a>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<h1 class="yellow-text text-darken-4"><%= t("title.article") %></h1>

<div class="row">
  <% @posts.each do |post| %>
    <%= render 'posts/post', {post: post} %>
  <% end %>
</div>

<h1 class="yellow-text text-darken-4"><%= t("title.news") %></h1>

<div class="row">
  <% @content['articles'].each do |article| %>
    <%= render "news/new", {article: article} %>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="row">
    <%= f.text_field :title, class: "input-field col s12 m4" %>
    <%= f.text_area :content, class: 'materialize-textarea col s12 m11' %>
    <%= f.submit post.new_record? ? 'Creer' : 'Modifier', class: "waves-effect waves-light btn  col m2" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="col s12 m6">
  <div class="card darken-1">

    <div class="card-content">
      <span class="card-title"><%= post.title %></span>
      <%= link_to post.user.username, user_infos_path(id: post.user.id) %>
      <p><%= truncate(post.content, :length => 100) %></p>
    </div>

    <div class="card-action">
      <%= link_to t("post.see"), post_path(id: post.id) %>
      <% if current_user == post.user %>
        <%= link_to t("post.edit"), [:edit, post] %>
        <%= link_to t("post.delete"), post, method: :delete %>
      <% end %>
    </div>

  </div>
</div>

app/views/posts/edit.html.erb
<h1>Modifier l'article</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h1 class="yellow-text text-darken-4">Articles</h1>

<% if flash[:notice] %>
  <div class="alert">
    <%= notice %>
  </div>
<% end %>
  <div class="row">
    <% @posts.each do |post| %>
      <%= render 'posts/post', {post: post} %>
    <% end %>
  </div>

<%= link_to 'Creer un article', new_post_path %>

app/views/posts/new.html.erb
<h1>Creer un article</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class="row">
  <h1 class="col s12 center-align"><%= @post.title %> </h1>
  <%= link_to @post.user.username, user_infos_path(id: @post.user.id) %>

  <p><%= @post.content %> </p>
  <div class="divider"></div>
  <div class="row">
  <h3 class="col">Commentaires</h3><p class="col">(<%= @post.comments.count %>)</p>
  </div>

  <%= render @post.comments %>
</div>
<%= @post.id %>
<%= render 'comments/form', {post: @post} %>

app/views/posts/user_posts.html.erb
<%= @user.username %>